branch-defaults:
  dep:
    environment: yourproject-env-dev
  develop:
    environment: yourproject-env-dev
    group_suffix: null
global:
  application_name: yourproject
  branch: develop
  default_ec2_keyname: null
  default_platform: Go
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: bin/bin.zip